#!/bin/bash
#=================================================================
#                                                                
#        FITXER:  zonadart                                     
# 
#            US:  ./zonadart 
# 
#    DESCRIPCIÓ:  Rutines de Zona d'Art
# 
#       OPCIONS:  ---
#  REQUIREMENTS:  --- mutt speedtest-cli ipcalc sipcalc secure-delete
#          BUGS:  ---
#         NOTES:  ---
#         AUTOR:  Gonçal Sallan i Baso (), zonadart@autistici.org
#     COMPANYIA:  Administració de Sistemes Linux
#        VERSIÓ:  2.0
#         CREAT:  27/11/09 13:56:11 CET
#       REVISIÓ:  03/07/18 13:56:11 CET
#=================================================================

clear
echo "M E N U :"
echo "========="
echo
echo "A) COMPTABILITAT"
echo "B) REPOSITORIS I APT"
echo "C) SEGURETAT"
echo "D) XARXES"
echo "E) SISTEMA"
echo "F) SERVIDORS"
echo "G) UTILITATS"
echo
echo "**********"
echo
echo "q) Sortir"
echo
echo "**********"

read opcio

case $opcio in

A)
sh /usr/bin/zonadart/compt.sh
;;

B)
sh /usr/bin/zonadart/repo.sh
;;

C)
sh /usr/bin/zonadart/sec.sh
;;

D)
sh /usr/bin/zonadart/xarx.sh
;;

E)
sh /usr/bin/zonadart/sist.sh
;;

F)
sh /usr/bin/zonadart/serv.sh
;;

G)
sh /usr/bin/zonadart/util.sh
;;

################################################# Sortir
q)
exit
;;
########### Opció invàlida
*)
echo Opció invàlida
###########################################################
esac

